[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "grupo_whatsapp"
version = "0.0.1"
description = "Proyecto para la clase de Ingenier\u00eda de Caracter\u00edsticas"
authors = [
  { name = "riotvann" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
dependencies = [
    "emoji>=2.16.0",
    "ipython",
    "jupyterlab",
    "loguru",
    "matplotlib",
    "notebook",
    "numpy",
    "pandas",
    "pip",
    "plotly>=7.1.0",
    "python-dotenv",
    "pyyaml>=6.0.3",
    "ruff",
    "scikit-learn",
    "spacy>=3.8.16",
    "tqdm",
    "typer",
]
requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["grupo_whatsapp"]
include = ["pyproject.toml", "grupo_whatsapp/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["grupo_whatsapp"]
force-sort-within-sections = true

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]

